#+title: disproofpoint

Demangle certain annoying corporate decisions.

* Status

Use this at your own risk.  It will likely destroy all that you hold
dear.  Not recommended for use by the "click every damn link" crowd.

* Command line 

As an mbox filter, it needs an output file holding *one* message:

#+BEGIN_EXAMPLE
  $ python3 disproofpoint.py mangled.mbox pristine.mbox
#+END_EXAMPLE

As a pipe filter, it will interpret the stream as *one* message and dump
out *one* message.  An mbox header is not included. 

#+BEGIN_EXAMPLE
  $ python3 disproofpoint.py < mangled.msg > pristine.msg
#+END_EXAMPLE


* Emacs

An implementation as an elisp function is provided in [[./disproofpoint.el]].

* Gnus

There are (at least) two ways to use integrate into Gnus.

One can pipe a message through the command line version by typing ~|~ in
the ~Summary~ buffer.

Or, to "wash" every article one can use the elisp function and this
bit of Gnus setup:

#+BEGIN_SRC lisp
(require 'disproofpoint)
(add-hook 'gnus-part-display-hook 'disproofpoint)
#+END_SRC


* To Do

- [ ] support multi-message mbox
- [ ] support Maildir 
- [ ] test with procmail
